structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/taxa/scientific_name?genus_name=123&species_name=leo", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:57:59 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "e87c4855-2e52-4dee-a8ec-bb5730c91088", 
        `X-Runtime` = "0.315498", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=1sZFqQCaUAP4VYgjb7xKLOtiHAlotqhSFVfpxOG3u5ojGyW4pzsEtVOpQd96%2FoNho3FiAWQko63gNoJdMPIlxhcagMPQNDZ4k%2FrhyLfArtsQobo%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962addfecc1163c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Not found\"}"), cache = new.env(parent = emptyenv())), class = "httr2_response")
