structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/stresses/TRUE?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:58:50 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "374a2971-63f9-4ee9-8147-0d90a94d3c8c", 
        `X-Runtime` = "0.011860", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=5BHjI5LNJfXNeeoHyyT%2FDOoKsKIOnK%2BsBIlCxfX3wsWuMq0a0itSYD03jGzeV6%2FYnxoUVqshI7wznyWnpKKAscg9o4Pohvyy%2BNDsti8GjWJmINI%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962adf3fda3d63c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Stress code TRUE not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
