structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/research/999?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:57:58 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "9ff42578-9579-488b-9432-a128a4542d43", 
        `X-Runtime` = "0.015936", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=TJWq1ct3fOLNPXCII7qk0tzuIGqgjM0ccLEq%2BScSl%2B3Nz6PWrs2xnWDJtwqbY8JBdIOBJShvdYiQJ5LqOW2qPZpC0dFGHC4pyiqpzQ3Z4DnIrnc%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962addf9d84263c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Research code 999 not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
