structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/research/invalid?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:57:56 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "9ce503c2-78e5-4d2d-9298-a82e7eb2a4a6", 
        `X-Runtime` = "0.011678", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=062fXE3CV8zvN8jvvqoE3R7rgyrZo9fItlnp5CzsQvmiJHooR3r%2BJ2AXdfCk3584%2FI8Yf2vfAYzBQFNRx%2BxTYWDmKx8MC8aEr9SMACGiHPRn22k%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962addf209bb63c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Research code invalid not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
