structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/research/TRUE?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:57:55 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "f2f8333e-ec84-42a4-895f-2caf2560cc21", 
        `X-Runtime` = "0.011478", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=mWu5Zw9zyUF71%2Flu6jrCde6UJV7%2BILuWaEs%2Ffcs8vc8IocusWmmm7r7%2B7zzWrgN1nr8Gg8VvipVHvZp8mdwZVUY2YtuNXIc4nV%2FBkZp%2BeNb0Wyw%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962addea6b5763c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Research code TRUE not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
