structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/growth_forms/123?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:56:06 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "dc6bb006-3147-45f7-a45d-4bf1ed29f431", 
        `X-Runtime` = "0.011523", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=hcPpE%2ByndNvjEO7z2eyPYp26lJgrR3jBBPiNw%2BsLCa1S0w%2FwYXC6zAARjCIk9xzATIM89oChY%2BA0aoivKkyMCxEP5djeK7diLT5e%2FTZ%2BlyhLTdg%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962adb3e183b63c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Growth Form code 123 not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
