structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/faos/999?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:55:37 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "d9a2c2e3-e98a-4659-9811-a523444cd126", 
        `X-Runtime` = "0.012447", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=GjcD1RzukdirXvB8zBPIa8S6yvBds16a7OhN%2Bjsm%2BUJDctYUpli8RcXPwhRR%2BdVALiDKOZKo%2FAm7omb3Hrd46Aaofvg%2B0bz8WxyDfECMOnvOH6o%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962ada88b98963c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"FAO code 999 not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
