structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/assessment/999999999", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:31:09 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "3d87e5c2-c01c-47ad-8caf-3670e590db9d", 
        `X-Runtime` = "0.013495", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=WTQyRTmnJ430xH%2FQASZiqxOobDWufuJQglu4a85ww5dnjdORtisz%2FDtFIEqtdOnB4wBhwMzBSsUzWKC%2B%2BxBcVNvUEO58NOBHpcfgMjltGYcl\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962ab6b5ac69ef2b-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Assessment ID 999999999 not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
