structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/use_and_trade/invalid_code?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:59:45 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "aea4f366-4ab3-4a72-8825-1038b2356901", 
        `X-Runtime` = "0.012857", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=EYITodDzYZihvuysr2foxGwN%2FocYA4caZlplMnjzn1%2F%2FZn%2Ba2bJTt%2FplW6FHZNp63Pjkuj%2F0qjsHFeS5IwkSFl4x1V8yWn8YckpkHswznsv%2Bsjw%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962ae0965d4163c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Use and Trade code invalid_code not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
