# R

library(testthat)
library(mockery)

test_that("rl_assessement_id calls dependencies and returns expected", {
  mock_rl_check_api <- mock()
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(a=1))
  mock_json_to_df <- mock(data.frame(a=1))
  stub(rl_assessement_id, "rl_check_api", mock_rl_check_api)
  stub(rl_assessement_id, "perform_request", mock_perform_request)
  stub(rl_assessement_id, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_assessement_id, "json_to_df", mock_json_to_df)
  res <- rl_assessement_id(123, pad_with_na=TRUE)
  expect_equal(res, data.frame(a=1))
  expect_called(mock_rl_check_api, 1)
  expect_called(mock_perform_request, 1)
  expect_called(mock_resp_body_json, 1)
  expect_called(mock_json_to_df, 1)
})

test_that("rl_biogeographical_realms returns list or calls paginated", {
  mock_rl_check_api <- mock()
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(b=2))
  mock_json_to_df <- mock(data.frame(b=2))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_biogeographical_realms, "rl_check_api", mock_rl_check_api)
  stub(rl_biogeographical_realms, "perform_request", mock_perform_request)
  stub(rl_biogeographical_realms, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_biogeographical_realms, "json_to_df", mock_json_to_df)
  stub(rl_biogeographical_realms, "rl_paginated_query", mock_rl_paginated_query)
  # code = NULL branch
  res1 <- rl_biogeographical_realms(code=NULL)
  expect_equal(res1, data.frame(b=2))
  # code != NULL branch
  res2 <- rl_biogeographical_realms(code=1)
  expect_equal(res2, "paginated")
})

test_that("rl_comprehensive_groups returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(c=3))
  mock_json_to_df <- mock(data.frame(c=3))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_comprehensive_groups, "perform_request", mock_perform_request)
  stub(rl_comprehensive_groups, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_comprehensive_groups, "json_to_df", mock_json_to_df)
  stub(rl_comprehensive_groups, "rl_paginated_query", mock_rl_paginated_query)
  # name = NULL branch
  res1 <- rl_comprehensive_groups(name=NULL)
  expect_equal(res1, data.frame(c=3))
  # name != NULL branch
  res2 <- rl_comprehensive_groups(name="amphibians")
  expect_equal(res2, "paginated")
})

test_that("rl_conservation_actions returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(d=4))
  mock_json_to_df <- mock(data.frame(d=4))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_conservation_actions, "perform_request", mock_perform_request)
  stub(rl_conservation_actions, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_conservation_actions, "json_to_df", mock_json_to_df)
  stub(rl_conservation_actions, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_conservation_actions(code=NULL)
  expect_equal(res1, data.frame(d=4))
  res2 <- rl_conservation_actions(code=1)
  expect_equal(res2, "paginated")
})

test_that("rl_countries returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(e=5))
  mock_json_to_df <- mock(data.frame(e=5))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_countries, "perform_request", mock_perform_request)
  stub(rl_countries, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_countries, "json_to_df", mock_json_to_df)
  stub(rl_countries, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_countries(code=NULL)
  expect_equal(res1, data.frame(e=5))
  res2 <- rl_countries(code="BR")
  expect_equal(res2, "paginated")
})

test_that("rl_faos returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(f=6))
  mock_json_to_df <- mock(data.frame(f=6))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_faos, "perform_request", mock_perform_request)
  stub(rl_faos, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_faos, "json_to_df", mock_json_to_df)
  stub(rl_faos, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_faos(code=NULL)
  expect_equal(res1, data.frame(f=6))
  res2 <- rl_faos(code="27")
  expect_equal(res2, "paginated")
})

test_that("rl_growth_forms returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(g=7))
  mock_json_to_df <- mock(data.frame(g=7))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_growth_forms, "perform_request", mock_perform_request)
  stub(rl_growth_forms, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_growth_forms, "json_to_df", mock_json_to_df)
  stub(rl_growth_forms, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_growth_forms(code=NULL)
  expect_equal(res1, data.frame(g=7))
  res2 <- rl_growth_forms(code="GE")
  expect_equal(res2, "paginated")
})

test_that("rl_green_status returns tibble", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(h=8))
  mock_json_to_df <- mock(data.frame(h=8))
  stub(rl_green_status, "perform_request", mock_perform_request)
  stub(rl_green_status, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_green_status, "json_to_df", mock_json_to_df)
  res <- rl_green_status(pad_with_na=TRUE)
  expect_equal(res, data.frame(h=8))
})

test_that("rl_habitats returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(i=9))
  mock_json_to_df <- mock(data.frame(i=9))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_habitats, "perform_request", mock_perform_request)
  stub(rl_habitats, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_habitats, "json_to_df", mock_json_to_df)
  stub(rl_habitats, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_habitats(code=NULL)
  expect_equal(res1, data.frame(i=9))
  res2 <- rl_habitats(code=8)
  expect_equal(res2, "paginated")
})

test_that("rl_version prints correct info", {
  mock_perform_request <- mock(list(red_list_version="2024"), list(api_version="1.2.3"))
  mock_resp_body_json <- mock(list(red_list_version="2024"), list(api_version="1.2.3"))
  mock_cli_div <- mock()
  mock_cli_alert_info <- mock()
  stub(rl_version, "perform_request", mock_perform_request)
  stub(rl_version, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_version, "cli::cli_div", mock_cli_div)
  stub(rl_version, "cli::cli_alert_info", mock_cli_alert_info)
  expect_invisible(rl_version())
  expect_called(mock_cli_alert_info, 2)
})

test_that("rl_population_trends returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(j=10))
  mock_json_to_df <- mock(data.frame(j=10))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_population_trends, "perform_request", mock_perform_request)
  stub(rl_population_trends, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_population_trends, "json_to_df", mock_json_to_df)
  stub(rl_population_trends, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_population_trends(code=NULL)
  expect_equal(res1, data.frame(j=10))
  res2 <- rl_population_trends(code=1)
  expect_equal(res2, "paginated")
})

test_that("rl_red_list_categories returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(k=11))
  mock_json_to_df <- mock(data.frame(k=11))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_red_list_categories, "perform_request", mock_perform_request)
  stub(rl_red_list_categories, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_red_list_categories, "json_to_df", mock_json_to_df)
  stub(rl_red_list_categories, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_red_list_categories(code=NULL)
  expect_equal(res1, data.frame(k=11))
  res2 <- rl_red_list_categories(code="CR")
  expect_equal(res2, "paginated")
})

test_that("rl_research returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(l=12))
  mock_json_to_df <- mock(data.frame(l=12))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_research, "perform_request", mock_perform_request)
  stub(rl_research, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_research, "json_to_df", mock_json_to_df)
  stub(rl_research, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_research(code=NULL)
  expect_equal(res1, data.frame(l=12))
  res2 <- rl_research(code="3_1")
  expect_equal(res2, "paginated")
})

test_that("rl_scopes returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(m=13))
  mock_json_to_df <- mock(data.frame(m=13))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_scopes, "perform_request", mock_perform_request)
  stub(rl_scopes, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_scopes, "json_to_df", mock_json_to_df)
  stub(rl_scopes, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_scopes(code=NULL)
  expect_equal(res1, data.frame(m=13))
  res2 <- rl_scopes(code="1")
  expect_equal(res2, "paginated")
})

test_that("rl_statistics returns tibble", {
  mock_perform_request <- mock(list(count="42"))
  mock_resp_body_json <- mock(list(count="42"))
  stub(rl_statistics, "perform_request", mock_perform_request)
  stub(rl_statistics, "httr2::resp_body_json", mock_resp_body_json)
  mock_as_tibble <- mock(data.frame(count=42, date_of_access=Sys.time()))
  stub(rl_statistics, "dplyr::as_tibble", mock_as_tibble)
  res <- rl_statistics()
  expect_true(is.data.frame(res))
  expect_equal(res$count, 42)
})

test_that("rl_stresses returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(n=14))
  mock_json_to_df <- mock(data.frame(n=14))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_stresses, "perform_request", mock_perform_request)
  stub(rl_stresses, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_stresses, "json_to_df", mock_json_to_df)
  stub(rl_stresses, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_stresses(code=NULL)
  expect_equal(res1, data.frame(n=14))
  res2 <- rl_stresses(code="1")
  expect_equal(res2, "paginated")
})

test_that("rl_systems returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(o=15))
  mock_json_to_df <- mock(data.frame(o=15))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_systems, "perform_request", mock_perform_request)
  stub(rl_systems, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_systems, "json_to_df", mock_json_to_df)
  stub(rl_systems, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_systems(code=NULL)
  expect_equal(res1, data.frame(o=15))
  res2 <- rl_systems(code=0)
  expect_equal(res2, "paginated")
})

test_that("rl_sis returns tibble", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(p=16))
  mock_json_to_df <- mock(data.frame(p=16))
  stub(rl_sis, "perform_request", mock_perform_request)
  stub(rl_sis, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_sis, "json_to_df", mock_json_to_df)
  res <- rl_sis(sis_id=123, pad_with_na=TRUE)
  expect_equal(res, data.frame(p=16))
})

test_that("rl_scientific_name returns tibble", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(q=17))
  mock_json_to_df <- mock(data.frame(q=17))
  stub(rl_scientific_name, "perform_request", mock_perform_request)
  stub(rl_scientific_name, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_scientific_name, "json_to_df", mock_json_to_df)
  res <- rl_scientific_name("Panthera", "leo", pad_with_na=TRUE)
  expect_equal(res, data.frame(q=17))
})

test_that("rl_kingdoms returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(r=18))
  mock_json_to_df <- mock(data.frame(r=18))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_kingdoms, "perform_request", mock_perform_request)
  stub(rl_kingdoms, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_kingdoms, "json_to_df", mock_json_to_df)
  stub(rl_kingdoms, "rl_paginated_query", mock_rl_paginated_query)
  # kingdom_name = NULL
  res1 <- rl_kingdoms(kingdom_name=NULL)
  expect_true(is.data.frame(res1))
  # kingdom_name != NULL
  res2 <- rl_kingdoms(kingdom_name="Animalia")
  expect_equal(res2, "paginated")
})

test_that("rl_phylum returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(s=19))
  mock_json_to_df <- mock(data.frame(s=19))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_phylum, "perform_request", mock_perform_request)
  stub(rl_phylum, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_phylum, "json_to_df", mock_json_to_df)
  stub(rl_phylum, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_phylum(phylum_name=NULL)
  expect_true(is.data.frame(res1))
  res2 <- rl_phylum(phylum_name="Chordata")
  expect_equal(res2, "paginated")
})

test_that("rl_classes returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(t=20))
  mock_json_to_df <- mock(data.frame(t=20))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_classes, "perform_request", mock_perform_request)
  stub(rl_classes, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_classes, "json_to_df", mock_json_to_df)
  stub(rl_classes, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_classes(class_name=NULL)
  expect_true(is.data.frame(res1))
  res2 <- rl_classes(class_name="Mammalia")
  expect_equal(res2, "paginated")
})

test_that("rl_orders returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(u=21))
  mock_json_to_df <- mock(data.frame(u=21))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_orders, "perform_request", mock_perform_request)
  stub(rl_orders, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_orders, "json_to_df", mock_json_to_df)
  stub(rl_orders, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_orders(order_name=NULL)
  expect_true(is.data.frame(res1))
  res2 <- rl_orders(order_name="Carnivora")
  expect_equal(res2, "paginated")
})

test_that("rl_family returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(v=22))
  mock_json_to_df <- mock(data.frame(v=22))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_family, "perform_request", mock_perform_request)
  stub(rl_family, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_family, "json_to_df", mock_json_to_df)
  stub(rl_family, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_family(family_name=NULL)
  expect_true(is.data.frame(res1))
  res2 <- rl_family(family_name="Felidae")
  expect_equal(res2, "paginated")
})

test_that("rl_possibly_extinct returns tibble", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(w=23))
  mock_json_to_df <- mock(data.frame(w=23))
  stub(rl_possibly_extinct, "perform_request", mock_perform_request)
  stub(rl_possibly_extinct, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_possibly_extinct, "json_to_df", mock_json_to_df)
  res <- rl_possibly_extinct(pad_with_na=TRUE)
  expect_equal(res, data.frame(w=23))
})

test_that("rl_possibly_extinct_in_wild returns tibble", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(x=24))
  mock_json_to_df <- mock(data.frame(x=24))
  stub(rl_possibly_extinct_in_wild, "perform_request", mock_perform_request)
  stub(rl_possibly_extinct_in_wild, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_possibly_extinct_in_wild, "json_to_df", mock_json_to_df)
  res <- rl_possibly_extinct_in_wild(pad_with_na=TRUE)
  expect_equal(res, data.frame(x=24))
})

test_that("rl_threats returns list or calls paginated", {
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(y=25))
  mock_json_to_df <- mock(data.frame(y=25))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_threats, "perform_request", mock_perform_request)
  stub(rl_threats, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_threats, "json_to_df", mock_json_to_df)
  stub(rl_threats, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_threats(code=NULL)
  expect_equal(res1, data.frame(y=25))
  res2 <- rl_threats(code="2")
  expect_equal(res2, "paginated")
})

test_that("rl_use_and_trade returns list or calls paginated", {
  mock_rl_check_api <- mock()
  mock_perform_request <- mock(list())
  mock_resp_body_json <- mock(list(z=26))
  mock_json_to_df <- mock(data.frame(z=26))
  mock_rl_paginated_query <- mock("paginated")
  stub(rl_use_and_trade, "rl_check_api", mock_rl_check_api)
  stub(rl_use_and_trade, "perform_request", mock_perform_request)
  stub(rl_use_and_trade, "httr2::resp_body_json", mock_resp_body_json)
  stub(rl_use_and_trade, "json_to_df", mock_json_to_df)
  stub(rl_use_and_trade, "rl_paginated_query", mock_rl_paginated_query)
  res1 <- rl_use_and_trade(code=NULL)
  expect_equal(res1, data.frame(z=26))
  res2 <- rl_use_and_trade(code="1")
  expect_equal(res2, "paginated")
})
