structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/habitats/TRUE?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:55:54 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "d5851b91-5a18-4344-8d87-ff497396ce7c", 
        `X-Runtime` = "0.015152", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=Lbk%2FOHSFoEUo5SXfdozWPN30%2BYMDJetaV48Ia1bkCjxKQu9NMPfd5xXrjRAA27vTq4FFRpn7jZ5shIF1C634wTYSwrKA5rFqLLc90jNce23an0c%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962adaf25fc763c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Habitat code TRUE not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
