structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/taxa/scientific_name?genus_name=Nonexistentia&species_name=imaginaris", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:58:01 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "9696dd82-d846-45df-8804-995d758245a8", 
        `X-Runtime` = "0.393239", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=4kNecL35UiqvpPJUrbUa0PU3UT0d9hAoxZkZwLApKndtUxvsVNZEiYGviIctMCacre6HPXyTyNEmtrcitcXZIHAkWxCXsgPYDxtrVjbjpK2rj5g%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962ade0c7fda63c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Not found\"}"), cache = new.env(parent = emptyenv())), class = "httr2_response")
