structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/comprehensive_groups/nonexistent_group?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:54:38 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "fd422ac6-12b5-4695-a074-b55e9fe7dbfa", 
        `X-Runtime` = "0.012364", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=pzaMIN%2BOxRA78fboyGml6tfqIn0Uw6lBWhbP6dG85WQfD0rZJIVQSGgEgm%2B9j8NpdUtd1JHcwExt1nfvhn6WJJUQrBVyJ2SvG%2Fg%2FQCKIUE2pVmE%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962ad9187b0963c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Comprehensive Group name nonexistent_group not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
