structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/countries/123?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:55:01 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "979868e9-23f4-4052-bc6a-e780e5724737", 
        `X-Runtime` = "0.015157", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=Y%2FYKqb%2B5Rj%2Fdq57RPxXpZD%2BSgs1429kDEmwsO5Ct2bCwsJqOcqVgGes6z%2BjGwEDa4BySJ3YZjnGsBzQhnbaI5QoI2RiL%2BHWvmq1cjHNYxABREpg%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962ad9ac2d9b63c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Country code 123 not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
