structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/red_list_categories/1?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:57:39 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "c1fa0748-4c54-4cef-bfd5-3a1e634b00d5", 
        `X-Runtime` = "0.013227", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=tLDfSk7CPP8AiNYbtSNZDl1NQSGrqA4rJ5Guv9EMK2nOYmikwemcs66V3FDQsU%2FiS9kHNY0S%2FkSzVKYrlfhshcR0zw11zxxLTfCq4EZGf4LGsz8%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962add8699c463c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Red List Category code 1 not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
