structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/red_list_categories/XX?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:57:41 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "aabdb374-f2ca-4fad-89c5-3c84440bb881", 
        `X-Runtime` = "0.011499", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=ElCvR3C7Jav00FUnDQLAiGPoTt6KGvH94P5YU51qLOHJWlaGyU0GN0JD1XUW55hgVSFLaV7RjT5GHotBwdfOsl6LztLfiXdqdZzyEGaGyAuoyy8%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962add8fe90263c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Red List Category code XX not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
