structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/scopes/TRUE?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:58:32 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "e3784c73-da66-4892-8d32-67c1c5067dad", 
        `X-Runtime` = "0.011612", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=aa8Kmw4Ad966Vx61YjKd%2F6WPUOPkjyjV2iUERxyXUjEdWXnNGpStRG1ESU3sJ0WI5DpEA%2FmficTWXQhuRt9%2F1WrNpWTZqLR4mC%2BNJ9%2B5juZBXZA%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962adeceed7a63c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Scope code TRUE not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
