structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/population_trends/999?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:57:22 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "cd8f5e2e-fb07-4285-9f8e-4b9d9fe05af2", 
        `X-Runtime` = "0.017659", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=d%2BvYbcSfSVlB3E%2BOEefbpFJveMSMziX22JU5Ibsgs128uAyyDdhCrqwjwQ5IPNBIC2tDj7YfvEH%2BRBNX7ds8%2F%2FujsgMifFE2lXMO33%2F23ECmZvU%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962add1e2f5263c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Population Trend code 999 not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
