structure(list(method = "GET", url = "https://api.iucnredlist.org/api/v4/population_trends/invalid?page=1", 
    status_code = 404L, headers = structure(list(Date = "Mon, 21 Jul 2025 12:57:21 GMT", 
        `Content-Type` = "application/json", `Transfer-Encoding` = "chunked", 
        Connection = "keep-alive", `Cache-Control` = "no-cache", 
        `X-Request-Id` = "89e6eac3-d36e-4d85-ad5d-f025ce80203b", 
        `X-Runtime` = "0.012171", `Cf-Cache-Status` = "DYNAMIC", 
        Nel = "{\"report_to\":\"cf-nel\",\"success_fraction\":0.0,\"max_age\":604800}", 
        `Speculation-Rules` = "\"/cdn-cgi/speculation\"", `Report-To` = "{\"group\":\"cf-nel\",\"max_age\":604800,\"endpoints\":[{\"url\":\"https://a.nel.cloudflare.com/report/v4?s=iQp4yCeHKCwZAVa9RM41JtomNLtmZ51KbIQOntOXUFD6719Qwv81VXqvc2bJ19CYBVPal2wf2Tsd4EVpgioXAtkn3xdkZEvjJb1ieAoWa%2BzFGyI%3D\"}]}", 
        `Content-Encoding` = "gzip", Server = "cloudflare", `CF-RAY` = "962add15df7a63c9-LHR", 
        `alt-svc` = "h3=\":443\"; ma=86400"), redact = character(0), class = "httr2_headers"), 
    body = charToRaw("{\"error\":\"Population Trend code invalid not found\"}"), 
    cache = new.env(parent = emptyenv())), class = "httr2_response")
